// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.java2nb.novel.entity.UserReadHistory;
import java.util.Date;

/**
 * @author 11797
 */
public class BookReadHistoryVO extends UserReadHistory {
    private Integer catId;
    private String catName;
    private Long lastIndexId;
    private String lastIndexName;
    private String bookName;
    @JsonFormat(timezone = "GMT+8", pattern = "MM/dd HH:mm:ss")
    private Date lastIndexUpdateTime;

    @Override
    public String toString() {
        return super.toString();
    }

    @java.lang.SuppressWarnings("all")
    public BookReadHistoryVO() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCatId() {
        return this.catId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCatName() {
        return this.catName;
    }

    @java.lang.SuppressWarnings("all")
    public Long getLastIndexId() {
        return this.lastIndexId;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastIndexName() {
        return this.lastIndexName;
    }

    @java.lang.SuppressWarnings("all")
    public String getBookName() {
        return this.bookName;
    }

    @java.lang.SuppressWarnings("all")
    public Date getLastIndexUpdateTime() {
        return this.lastIndexUpdateTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setCatId(final Integer catId) {
        this.catId = catId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCatName(final String catName) {
        this.catName = catName;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastIndexId(final Long lastIndexId) {
        this.lastIndexId = lastIndexId;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastIndexName(final String lastIndexName) {
        this.lastIndexName = lastIndexName;
    }

    @java.lang.SuppressWarnings("all")
    public void setBookName(final String bookName) {
        this.bookName = bookName;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastIndexUpdateTime(final Date lastIndexUpdateTime) {
        this.lastIndexUpdateTime = lastIndexUpdateTime;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BookReadHistoryVO)) return false;
        final BookReadHistoryVO other = (BookReadHistoryVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$catId = this.getCatId();
        final java.lang.Object other$catId = other.getCatId();
        if (this$catId == null ? other$catId != null : !this$catId.equals(other$catId)) return false;
        final java.lang.Object this$catName = this.getCatName();
        final java.lang.Object other$catName = other.getCatName();
        if (this$catName == null ? other$catName != null : !this$catName.equals(other$catName)) return false;
        final java.lang.Object this$lastIndexId = this.getLastIndexId();
        final java.lang.Object other$lastIndexId = other.getLastIndexId();
        if (this$lastIndexId == null ? other$lastIndexId != null : !this$lastIndexId.equals(other$lastIndexId)) return false;
        final java.lang.Object this$lastIndexName = this.getLastIndexName();
        final java.lang.Object other$lastIndexName = other.getLastIndexName();
        if (this$lastIndexName == null ? other$lastIndexName != null : !this$lastIndexName.equals(other$lastIndexName)) return false;
        final java.lang.Object this$bookName = this.getBookName();
        final java.lang.Object other$bookName = other.getBookName();
        if (this$bookName == null ? other$bookName != null : !this$bookName.equals(other$bookName)) return false;
        final java.lang.Object this$lastIndexUpdateTime = this.getLastIndexUpdateTime();
        final java.lang.Object other$lastIndexUpdateTime = other.getLastIndexUpdateTime();
        if (this$lastIndexUpdateTime == null ? other$lastIndexUpdateTime != null : !this$lastIndexUpdateTime.equals(other$lastIndexUpdateTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BookReadHistoryVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $catId = this.getCatId();
        result = result * PRIME + ($catId == null ? 43 : $catId.hashCode());
        final java.lang.Object $catName = this.getCatName();
        result = result * PRIME + ($catName == null ? 43 : $catName.hashCode());
        final java.lang.Object $lastIndexId = this.getLastIndexId();
        result = result * PRIME + ($lastIndexId == null ? 43 : $lastIndexId.hashCode());
        final java.lang.Object $lastIndexName = this.getLastIndexName();
        result = result * PRIME + ($lastIndexName == null ? 43 : $lastIndexName.hashCode());
        final java.lang.Object $bookName = this.getBookName();
        result = result * PRIME + ($bookName == null ? 43 : $bookName.hashCode());
        final java.lang.Object $lastIndexUpdateTime = this.getLastIndexUpdateTime();
        result = result * PRIME + ($lastIndexUpdateTime == null ? 43 : $lastIndexUpdateTime.hashCode());
        return result;
    }
}
