// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.vo;

import com.java2nb.novel.entity.BookSetting;
import java.io.Serializable;

/**
 * @author 11797
 */
public class BookSettingVO extends BookSetting implements Serializable {
    private String bookName;
    private String picUrl;
    private String authorName;
    private String bookDesc;
    private Float score;
    private Integer catId;
    private String catName;
    private Byte bookStatus;

    @Override
    public String toString() {
        return super.toString();
    }

    @java.lang.SuppressWarnings("all")
    public BookSettingVO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getBookName() {
        return this.bookName;
    }

    @java.lang.SuppressWarnings("all")
    public String getPicUrl() {
        return this.picUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getAuthorName() {
        return this.authorName;
    }

    @java.lang.SuppressWarnings("all")
    public String getBookDesc() {
        return this.bookDesc;
    }

    @java.lang.SuppressWarnings("all")
    public Float getScore() {
        return this.score;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCatId() {
        return this.catId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCatName() {
        return this.catName;
    }

    @java.lang.SuppressWarnings("all")
    public Byte getBookStatus() {
        return this.bookStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setBookName(final String bookName) {
        this.bookName = bookName;
    }

    @java.lang.SuppressWarnings("all")
    public void setPicUrl(final String picUrl) {
        this.picUrl = picUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setAuthorName(final String authorName) {
        this.authorName = authorName;
    }

    @java.lang.SuppressWarnings("all")
    public void setBookDesc(final String bookDesc) {
        this.bookDesc = bookDesc;
    }

    @java.lang.SuppressWarnings("all")
    public void setScore(final Float score) {
        this.score = score;
    }

    @java.lang.SuppressWarnings("all")
    public void setCatId(final Integer catId) {
        this.catId = catId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCatName(final String catName) {
        this.catName = catName;
    }

    @java.lang.SuppressWarnings("all")
    public void setBookStatus(final Byte bookStatus) {
        this.bookStatus = bookStatus;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BookSettingVO)) return false;
        final BookSettingVO other = (BookSettingVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$bookName = this.getBookName();
        final java.lang.Object other$bookName = other.getBookName();
        if (this$bookName == null ? other$bookName != null : !this$bookName.equals(other$bookName)) return false;
        final java.lang.Object this$picUrl = this.getPicUrl();
        final java.lang.Object other$picUrl = other.getPicUrl();
        if (this$picUrl == null ? other$picUrl != null : !this$picUrl.equals(other$picUrl)) return false;
        final java.lang.Object this$authorName = this.getAuthorName();
        final java.lang.Object other$authorName = other.getAuthorName();
        if (this$authorName == null ? other$authorName != null : !this$authorName.equals(other$authorName)) return false;
        final java.lang.Object this$bookDesc = this.getBookDesc();
        final java.lang.Object other$bookDesc = other.getBookDesc();
        if (this$bookDesc == null ? other$bookDesc != null : !this$bookDesc.equals(other$bookDesc)) return false;
        final java.lang.Object this$score = this.getScore();
        final java.lang.Object other$score = other.getScore();
        if (this$score == null ? other$score != null : !this$score.equals(other$score)) return false;
        final java.lang.Object this$catId = this.getCatId();
        final java.lang.Object other$catId = other.getCatId();
        if (this$catId == null ? other$catId != null : !this$catId.equals(other$catId)) return false;
        final java.lang.Object this$catName = this.getCatName();
        final java.lang.Object other$catName = other.getCatName();
        if (this$catName == null ? other$catName != null : !this$catName.equals(other$catName)) return false;
        final java.lang.Object this$bookStatus = this.getBookStatus();
        final java.lang.Object other$bookStatus = other.getBookStatus();
        if (this$bookStatus == null ? other$bookStatus != null : !this$bookStatus.equals(other$bookStatus)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BookSettingVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $bookName = this.getBookName();
        result = result * PRIME + ($bookName == null ? 43 : $bookName.hashCode());
        final java.lang.Object $picUrl = this.getPicUrl();
        result = result * PRIME + ($picUrl == null ? 43 : $picUrl.hashCode());
        final java.lang.Object $authorName = this.getAuthorName();
        result = result * PRIME + ($authorName == null ? 43 : $authorName.hashCode());
        final java.lang.Object $bookDesc = this.getBookDesc();
        result = result * PRIME + ($bookDesc == null ? 43 : $bookDesc.hashCode());
        final java.lang.Object $score = this.getScore();
        result = result * PRIME + ($score == null ? 43 : $score.hashCode());
        final java.lang.Object $catId = this.getCatId();
        result = result * PRIME + ($catId == null ? 43 : $catId.hashCode());
        final java.lang.Object $catName = this.getCatName();
        result = result * PRIME + ($catName == null ? 43 : $catName.hashCode());
        final java.lang.Object $bookStatus = this.getBookStatus();
        result = result * PRIME + ($bookStatus == null ? 43 : $bookStatus.hashCode());
        return result;
    }
}
