// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.vo;

/**
 * @author Administrator
 */
public class EsBookVO {
    private Long id;
    private Byte workDirection;
    private Integer catId;
    private String catName;
    private String picUrl;
    private String bookName;
    private Long authorId;
    private String authorName;
    private String bookDesc;
    private Float score;
    private Byte bookStatus;
    private Long visitCount;
    private Integer wordCount;
    private Integer commentCount;
    private Long lastIndexId;
    private String lastIndexName;
    private String lastIndexUpdateTime;
    private Byte isVip;
    private Byte status;
    private Integer crawlSourceId;
    private String crawlBookId;
    private Byte crawlIsStop;

    @java.lang.SuppressWarnings("all")
    public EsBookVO() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Byte getWorkDirection() {
        return this.workDirection;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCatId() {
        return this.catId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCatName() {
        return this.catName;
    }

    @java.lang.SuppressWarnings("all")
    public String getPicUrl() {
        return this.picUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getBookName() {
        return this.bookName;
    }

    @java.lang.SuppressWarnings("all")
    public Long getAuthorId() {
        return this.authorId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAuthorName() {
        return this.authorName;
    }

    @java.lang.SuppressWarnings("all")
    public String getBookDesc() {
        return this.bookDesc;
    }

    @java.lang.SuppressWarnings("all")
    public Float getScore() {
        return this.score;
    }

    @java.lang.SuppressWarnings("all")
    public Byte getBookStatus() {
        return this.bookStatus;
    }

    @java.lang.SuppressWarnings("all")
    public Long getVisitCount() {
        return this.visitCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getWordCount() {
        return this.wordCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCommentCount() {
        return this.commentCount;
    }

    @java.lang.SuppressWarnings("all")
    public Long getLastIndexId() {
        return this.lastIndexId;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastIndexName() {
        return this.lastIndexName;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastIndexUpdateTime() {
        return this.lastIndexUpdateTime;
    }

    @java.lang.SuppressWarnings("all")
    public Byte getIsVip() {
        return this.isVip;
    }

    @java.lang.SuppressWarnings("all")
    public Byte getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCrawlSourceId() {
        return this.crawlSourceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCrawlBookId() {
        return this.crawlBookId;
    }

    @java.lang.SuppressWarnings("all")
    public Byte getCrawlIsStop() {
        return this.crawlIsStop;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setWorkDirection(final Byte workDirection) {
        this.workDirection = workDirection;
    }

    @java.lang.SuppressWarnings("all")
    public void setCatId(final Integer catId) {
        this.catId = catId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCatName(final String catName) {
        this.catName = catName;
    }

    @java.lang.SuppressWarnings("all")
    public void setPicUrl(final String picUrl) {
        this.picUrl = picUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setBookName(final String bookName) {
        this.bookName = bookName;
    }

    @java.lang.SuppressWarnings("all")
    public void setAuthorId(final Long authorId) {
        this.authorId = authorId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAuthorName(final String authorName) {
        this.authorName = authorName;
    }

    @java.lang.SuppressWarnings("all")
    public void setBookDesc(final String bookDesc) {
        this.bookDesc = bookDesc;
    }

    @java.lang.SuppressWarnings("all")
    public void setScore(final Float score) {
        this.score = score;
    }

    @java.lang.SuppressWarnings("all")
    public void setBookStatus(final Byte bookStatus) {
        this.bookStatus = bookStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setVisitCount(final Long visitCount) {
        this.visitCount = visitCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setWordCount(final Integer wordCount) {
        this.wordCount = wordCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCommentCount(final Integer commentCount) {
        this.commentCount = commentCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastIndexId(final Long lastIndexId) {
        this.lastIndexId = lastIndexId;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastIndexName(final String lastIndexName) {
        this.lastIndexName = lastIndexName;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastIndexUpdateTime(final String lastIndexUpdateTime) {
        this.lastIndexUpdateTime = lastIndexUpdateTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsVip(final Byte isVip) {
        this.isVip = isVip;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Byte status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setCrawlSourceId(final Integer crawlSourceId) {
        this.crawlSourceId = crawlSourceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCrawlBookId(final String crawlBookId) {
        this.crawlBookId = crawlBookId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCrawlIsStop(final Byte crawlIsStop) {
        this.crawlIsStop = crawlIsStop;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EsBookVO)) return false;
        final EsBookVO other = (EsBookVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$workDirection = this.getWorkDirection();
        final java.lang.Object other$workDirection = other.getWorkDirection();
        if (this$workDirection == null ? other$workDirection != null : !this$workDirection.equals(other$workDirection)) return false;
        final java.lang.Object this$catId = this.getCatId();
        final java.lang.Object other$catId = other.getCatId();
        if (this$catId == null ? other$catId != null : !this$catId.equals(other$catId)) return false;
        final java.lang.Object this$catName = this.getCatName();
        final java.lang.Object other$catName = other.getCatName();
        if (this$catName == null ? other$catName != null : !this$catName.equals(other$catName)) return false;
        final java.lang.Object this$picUrl = this.getPicUrl();
        final java.lang.Object other$picUrl = other.getPicUrl();
        if (this$picUrl == null ? other$picUrl != null : !this$picUrl.equals(other$picUrl)) return false;
        final java.lang.Object this$bookName = this.getBookName();
        final java.lang.Object other$bookName = other.getBookName();
        if (this$bookName == null ? other$bookName != null : !this$bookName.equals(other$bookName)) return false;
        final java.lang.Object this$authorId = this.getAuthorId();
        final java.lang.Object other$authorId = other.getAuthorId();
        if (this$authorId == null ? other$authorId != null : !this$authorId.equals(other$authorId)) return false;
        final java.lang.Object this$authorName = this.getAuthorName();
        final java.lang.Object other$authorName = other.getAuthorName();
        if (this$authorName == null ? other$authorName != null : !this$authorName.equals(other$authorName)) return false;
        final java.lang.Object this$bookDesc = this.getBookDesc();
        final java.lang.Object other$bookDesc = other.getBookDesc();
        if (this$bookDesc == null ? other$bookDesc != null : !this$bookDesc.equals(other$bookDesc)) return false;
        final java.lang.Object this$score = this.getScore();
        final java.lang.Object other$score = other.getScore();
        if (this$score == null ? other$score != null : !this$score.equals(other$score)) return false;
        final java.lang.Object this$bookStatus = this.getBookStatus();
        final java.lang.Object other$bookStatus = other.getBookStatus();
        if (this$bookStatus == null ? other$bookStatus != null : !this$bookStatus.equals(other$bookStatus)) return false;
        final java.lang.Object this$visitCount = this.getVisitCount();
        final java.lang.Object other$visitCount = other.getVisitCount();
        if (this$visitCount == null ? other$visitCount != null : !this$visitCount.equals(other$visitCount)) return false;
        final java.lang.Object this$wordCount = this.getWordCount();
        final java.lang.Object other$wordCount = other.getWordCount();
        if (this$wordCount == null ? other$wordCount != null : !this$wordCount.equals(other$wordCount)) return false;
        final java.lang.Object this$commentCount = this.getCommentCount();
        final java.lang.Object other$commentCount = other.getCommentCount();
        if (this$commentCount == null ? other$commentCount != null : !this$commentCount.equals(other$commentCount)) return false;
        final java.lang.Object this$lastIndexId = this.getLastIndexId();
        final java.lang.Object other$lastIndexId = other.getLastIndexId();
        if (this$lastIndexId == null ? other$lastIndexId != null : !this$lastIndexId.equals(other$lastIndexId)) return false;
        final java.lang.Object this$lastIndexName = this.getLastIndexName();
        final java.lang.Object other$lastIndexName = other.getLastIndexName();
        if (this$lastIndexName == null ? other$lastIndexName != null : !this$lastIndexName.equals(other$lastIndexName)) return false;
        final java.lang.Object this$lastIndexUpdateTime = this.getLastIndexUpdateTime();
        final java.lang.Object other$lastIndexUpdateTime = other.getLastIndexUpdateTime();
        if (this$lastIndexUpdateTime == null ? other$lastIndexUpdateTime != null : !this$lastIndexUpdateTime.equals(other$lastIndexUpdateTime)) return false;
        final java.lang.Object this$isVip = this.getIsVip();
        final java.lang.Object other$isVip = other.getIsVip();
        if (this$isVip == null ? other$isVip != null : !this$isVip.equals(other$isVip)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$crawlSourceId = this.getCrawlSourceId();
        final java.lang.Object other$crawlSourceId = other.getCrawlSourceId();
        if (this$crawlSourceId == null ? other$crawlSourceId != null : !this$crawlSourceId.equals(other$crawlSourceId)) return false;
        final java.lang.Object this$crawlBookId = this.getCrawlBookId();
        final java.lang.Object other$crawlBookId = other.getCrawlBookId();
        if (this$crawlBookId == null ? other$crawlBookId != null : !this$crawlBookId.equals(other$crawlBookId)) return false;
        final java.lang.Object this$crawlIsStop = this.getCrawlIsStop();
        final java.lang.Object other$crawlIsStop = other.getCrawlIsStop();
        if (this$crawlIsStop == null ? other$crawlIsStop != null : !this$crawlIsStop.equals(other$crawlIsStop)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EsBookVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $workDirection = this.getWorkDirection();
        result = result * PRIME + ($workDirection == null ? 43 : $workDirection.hashCode());
        final java.lang.Object $catId = this.getCatId();
        result = result * PRIME + ($catId == null ? 43 : $catId.hashCode());
        final java.lang.Object $catName = this.getCatName();
        result = result * PRIME + ($catName == null ? 43 : $catName.hashCode());
        final java.lang.Object $picUrl = this.getPicUrl();
        result = result * PRIME + ($picUrl == null ? 43 : $picUrl.hashCode());
        final java.lang.Object $bookName = this.getBookName();
        result = result * PRIME + ($bookName == null ? 43 : $bookName.hashCode());
        final java.lang.Object $authorId = this.getAuthorId();
        result = result * PRIME + ($authorId == null ? 43 : $authorId.hashCode());
        final java.lang.Object $authorName = this.getAuthorName();
        result = result * PRIME + ($authorName == null ? 43 : $authorName.hashCode());
        final java.lang.Object $bookDesc = this.getBookDesc();
        result = result * PRIME + ($bookDesc == null ? 43 : $bookDesc.hashCode());
        final java.lang.Object $score = this.getScore();
        result = result * PRIME + ($score == null ? 43 : $score.hashCode());
        final java.lang.Object $bookStatus = this.getBookStatus();
        result = result * PRIME + ($bookStatus == null ? 43 : $bookStatus.hashCode());
        final java.lang.Object $visitCount = this.getVisitCount();
        result = result * PRIME + ($visitCount == null ? 43 : $visitCount.hashCode());
        final java.lang.Object $wordCount = this.getWordCount();
        result = result * PRIME + ($wordCount == null ? 43 : $wordCount.hashCode());
        final java.lang.Object $commentCount = this.getCommentCount();
        result = result * PRIME + ($commentCount == null ? 43 : $commentCount.hashCode());
        final java.lang.Object $lastIndexId = this.getLastIndexId();
        result = result * PRIME + ($lastIndexId == null ? 43 : $lastIndexId.hashCode());
        final java.lang.Object $lastIndexName = this.getLastIndexName();
        result = result * PRIME + ($lastIndexName == null ? 43 : $lastIndexName.hashCode());
        final java.lang.Object $lastIndexUpdateTime = this.getLastIndexUpdateTime();
        result = result * PRIME + ($lastIndexUpdateTime == null ? 43 : $lastIndexUpdateTime.hashCode());
        final java.lang.Object $isVip = this.getIsVip();
        result = result * PRIME + ($isVip == null ? 43 : $isVip.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $crawlSourceId = this.getCrawlSourceId();
        result = result * PRIME + ($crawlSourceId == null ? 43 : $crawlSourceId.hashCode());
        final java.lang.Object $crawlBookId = this.getCrawlBookId();
        result = result * PRIME + ($crawlBookId == null ? 43 : $crawlBookId.hashCode());
        final java.lang.Object $crawlIsStop = this.getCrawlIsStop();
        result = result * PRIME + ($crawlIsStop == null ? 43 : $crawlIsStop.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "EsBookVO(id=" + this.getId() + ", workDirection=" + this.getWorkDirection() + ", catId=" + this.getCatId() + ", catName=" + this.getCatName() + ", picUrl=" + this.getPicUrl() + ", bookName=" + this.getBookName() + ", authorId=" + this.getAuthorId() + ", authorName=" + this.getAuthorName() + ", bookDesc=" + this.getBookDesc() + ", score=" + this.getScore() + ", bookStatus=" + this.getBookStatus() + ", visitCount=" + this.getVisitCount() + ", wordCount=" + this.getWordCount() + ", commentCount=" + this.getCommentCount() + ", lastIndexId=" + this.getLastIndexId() + ", lastIndexName=" + this.getLastIndexName() + ", lastIndexUpdateTime=" + this.getLastIndexUpdateTime() + ", isVip=" + this.getIsVip() + ", status=" + this.getStatus() + ", crawlSourceId=" + this.getCrawlSourceId() + ", crawlBookId=" + this.getCrawlBookId() + ", crawlIsStop=" + this.getCrawlIsStop() + ")";
    }
}
