// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.controller;

import com.java2nb.novel.entity.FriendLink;
import com.java2nb.novel.service.FriendLinkService;
import io.github.xxyopen.model.resp.RestResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import java.util.List;

/**
 * @author 11797
 */
@RequestMapping("friendLink")
@RestController
public class FriendLinkController {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(FriendLinkController.class);
    private final FriendLinkService friendLinkService;

    /**
     * 查询首页友情链接
     */
    @GetMapping("listIndexLink")
    public RestResult<List<FriendLink>> listIndexLink() {
        return RestResult.ok(friendLinkService.listIndexLink());
    }

    @java.lang.SuppressWarnings("all")
    public FriendLinkController(final FriendLinkService friendLinkService) {
        this.friendLinkService = friendLinkService;
    }
}
