// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.controller;

import com.github.pagehelper.PageInfo;
import io.github.xxyopen.model.page.PageBean;
import com.java2nb.novel.entity.News;
import com.java2nb.novel.service.NewsService;
import io.github.xxyopen.model.resp.RestResult;
import org.springframework.web.bind.annotation.*;
import java.util.List;

/**
 * @author 11797
 */
@RequestMapping("news")
@RestController
public class NewsController {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(NewsController.class);
    private final NewsService newsService;

    /**
     * 查询首页新闻
     */
    @GetMapping("listIndexNews")
    public RestResult<List<News>> listIndexNews() {
        return RestResult.ok(newsService.listIndexNews());
    }

    /**
     * 分页查询新闻列表
     */
    @GetMapping("listByPage")
    public RestResult<PageBean<News>> listByPage(@RequestParam(value = "curr", defaultValue = "1") int page, @RequestParam(value = "limit", defaultValue = "5") int pageSize) {
        return RestResult.ok(newsService.listByPage(page, pageSize));
    }

    /**
     * 增加新闻阅读量
     */
    @PostMapping("addReadCount")
    public RestResult<Void> addReadCount(@RequestParam("newsId") Integer newsId) {
        newsService.addReadCount(newsId);
        return RestResult.ok();
    }

    @java.lang.SuppressWarnings("all")
    public NewsController(final NewsService newsService) {
        this.newsService = newsService;
    }
}
