// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.core.listener;

import com.java2nb.novel.core.config.WebsiteProperties;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;

/**
 * 启动监听器
 * @author xiongxiaoyang
 */
@WebListener
public class StarterListener implements ServletContextListener {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(StarterListener.class);
    private final WebsiteProperties websiteConfig;

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        sce.getServletContext().setAttribute("website", websiteConfig);
    }

    @java.lang.SuppressWarnings("all")
    public StarterListener(final WebsiteProperties websiteConfig) {
        this.websiteConfig = websiteConfig;
    }
}
