// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.service.impl;

import com.java2nb.novel.entity.BookContent;
import com.java2nb.novel.service.BookContentService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.io.BufferedReader;
import java.io.FileReader;

@Service("txt")
public class FileBookContentServiceImpl implements BookContentService {
    @Value("${content.save.path}")
    private String fileSavePath;

    @Override
    public BookContent queryBookContent(Long bookId, Long bookIndexId) {
        try {
            BufferedReader in = new BufferedReader(new FileReader(fileSavePath + "/" + bookId + "/" + bookIndexId + ".txt"));
            StringBuffer sb = new StringBuffer();
            String str;
            while ((str = in.readLine()) != null) {
                sb.append(str);
            }
            in.close();
            return new BookContent() {
                {
                    setIndexId(bookIndexId);
                    setContent(sb.toString());
                }
            };
        } catch (final java.lang.Throwable $ex) {
            throw lombok.Lombok.sneakyThrow($ex);
        }
    }

    @java.lang.SuppressWarnings("all")
    public FileBookContentServiceImpl() {
    }
}
