// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.core.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

/**
 * @author 11797
 */
@Component
@ConfigurationProperties(prefix = "alipay")
public class AlipayProperties {
    private String appId;
    private String merchantPrivateKey;
    private String publicKey;
    private String notifyUrl;
    private String returnUrl;
    private String signType;
    private String charset;
    private String gatewayUrl;

    @java.lang.SuppressWarnings("all")
    public AlipayProperties() {
    }

    @java.lang.SuppressWarnings("all")
    public String getAppId() {
        return this.appId;
    }

    @java.lang.SuppressWarnings("all")
    public String getMerchantPrivateKey() {
        return this.merchantPrivateKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getPublicKey() {
        return this.publicKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getNotifyUrl() {
        return this.notifyUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getReturnUrl() {
        return this.returnUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getSignType() {
        return this.signType;
    }

    @java.lang.SuppressWarnings("all")
    public String getCharset() {
        return this.charset;
    }

    @java.lang.SuppressWarnings("all")
    public String getGatewayUrl() {
        return this.gatewayUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setAppId(final String appId) {
        this.appId = appId;
    }

    @java.lang.SuppressWarnings("all")
    public void setMerchantPrivateKey(final String merchantPrivateKey) {
        this.merchantPrivateKey = merchantPrivateKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setPublicKey(final String publicKey) {
        this.publicKey = publicKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotifyUrl(final String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setReturnUrl(final String returnUrl) {
        this.returnUrl = returnUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setSignType(final String signType) {
        this.signType = signType;
    }

    @java.lang.SuppressWarnings("all")
    public void setCharset(final String charset) {
        this.charset = charset;
    }

    @java.lang.SuppressWarnings("all")
    public void setGatewayUrl(final String gatewayUrl) {
        this.gatewayUrl = gatewayUrl;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AlipayProperties)) return false;
        final AlipayProperties other = (AlipayProperties) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$appId = this.getAppId();
        final java.lang.Object other$appId = other.getAppId();
        if (this$appId == null ? other$appId != null : !this$appId.equals(other$appId)) return false;
        final java.lang.Object this$merchantPrivateKey = this.getMerchantPrivateKey();
        final java.lang.Object other$merchantPrivateKey = other.getMerchantPrivateKey();
        if (this$merchantPrivateKey == null ? other$merchantPrivateKey != null : !this$merchantPrivateKey.equals(other$merchantPrivateKey)) return false;
        final java.lang.Object this$publicKey = this.getPublicKey();
        final java.lang.Object other$publicKey = other.getPublicKey();
        if (this$publicKey == null ? other$publicKey != null : !this$publicKey.equals(other$publicKey)) return false;
        final java.lang.Object this$notifyUrl = this.getNotifyUrl();
        final java.lang.Object other$notifyUrl = other.getNotifyUrl();
        if (this$notifyUrl == null ? other$notifyUrl != null : !this$notifyUrl.equals(other$notifyUrl)) return false;
        final java.lang.Object this$returnUrl = this.getReturnUrl();
        final java.lang.Object other$returnUrl = other.getReturnUrl();
        if (this$returnUrl == null ? other$returnUrl != null : !this$returnUrl.equals(other$returnUrl)) return false;
        final java.lang.Object this$signType = this.getSignType();
        final java.lang.Object other$signType = other.getSignType();
        if (this$signType == null ? other$signType != null : !this$signType.equals(other$signType)) return false;
        final java.lang.Object this$charset = this.getCharset();
        final java.lang.Object other$charset = other.getCharset();
        if (this$charset == null ? other$charset != null : !this$charset.equals(other$charset)) return false;
        final java.lang.Object this$gatewayUrl = this.getGatewayUrl();
        final java.lang.Object other$gatewayUrl = other.getGatewayUrl();
        if (this$gatewayUrl == null ? other$gatewayUrl != null : !this$gatewayUrl.equals(other$gatewayUrl)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AlipayProperties;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $appId = this.getAppId();
        result = result * PRIME + ($appId == null ? 43 : $appId.hashCode());
        final java.lang.Object $merchantPrivateKey = this.getMerchantPrivateKey();
        result = result * PRIME + ($merchantPrivateKey == null ? 43 : $merchantPrivateKey.hashCode());
        final java.lang.Object $publicKey = this.getPublicKey();
        result = result * PRIME + ($publicKey == null ? 43 : $publicKey.hashCode());
        final java.lang.Object $notifyUrl = this.getNotifyUrl();
        result = result * PRIME + ($notifyUrl == null ? 43 : $notifyUrl.hashCode());
        final java.lang.Object $returnUrl = this.getReturnUrl();
        result = result * PRIME + ($returnUrl == null ? 43 : $returnUrl.hashCode());
        final java.lang.Object $signType = this.getSignType();
        result = result * PRIME + ($signType == null ? 43 : $signType.hashCode());
        final java.lang.Object $charset = this.getCharset();
        result = result * PRIME + ($charset == null ? 43 : $charset.hashCode());
        final java.lang.Object $gatewayUrl = this.getGatewayUrl();
        result = result * PRIME + ($gatewayUrl == null ? 43 : $gatewayUrl.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AlipayProperties(appId=" + this.getAppId() + ", merchantPrivateKey=" + this.getMerchantPrivateKey() + ", publicKey=" + this.getPublicKey() + ", notifyUrl=" + this.getNotifyUrl() + ", returnUrl=" + this.getReturnUrl() + ", signType=" + this.getSignType() + ", charset=" + this.getCharset() + ", gatewayUrl=" + this.getGatewayUrl() + ")";
    }
}
