// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.core.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;
import java.math.BigDecimal;

/**
 * 作家收入配置属性
 * @author cd
 */
@Component
@ConfigurationProperties(prefix = "author.income")
public class AuthorIncomeProperties {
    private BigDecimal taxRate;
    private BigDecimal shareProportion;
    private BigDecimal exchangeProportion;

    @java.lang.SuppressWarnings("all")
    public AuthorIncomeProperties() {
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getTaxRate() {
        return this.taxRate;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getShareProportion() {
        return this.shareProportion;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getExchangeProportion() {
        return this.exchangeProportion;
    }

    @java.lang.SuppressWarnings("all")
    public void setTaxRate(final BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    @java.lang.SuppressWarnings("all")
    public void setShareProportion(final BigDecimal shareProportion) {
        this.shareProportion = shareProportion;
    }

    @java.lang.SuppressWarnings("all")
    public void setExchangeProportion(final BigDecimal exchangeProportion) {
        this.exchangeProportion = exchangeProportion;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthorIncomeProperties)) return false;
        final AuthorIncomeProperties other = (AuthorIncomeProperties) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$taxRate = this.getTaxRate();
        final java.lang.Object other$taxRate = other.getTaxRate();
        if (this$taxRate == null ? other$taxRate != null : !this$taxRate.equals(other$taxRate)) return false;
        final java.lang.Object this$shareProportion = this.getShareProportion();
        final java.lang.Object other$shareProportion = other.getShareProportion();
        if (this$shareProportion == null ? other$shareProportion != null : !this$shareProportion.equals(other$shareProportion)) return false;
        final java.lang.Object this$exchangeProportion = this.getExchangeProportion();
        final java.lang.Object other$exchangeProportion = other.getExchangeProportion();
        if (this$exchangeProportion == null ? other$exchangeProportion != null : !this$exchangeProportion.equals(other$exchangeProportion)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthorIncomeProperties;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $taxRate = this.getTaxRate();
        result = result * PRIME + ($taxRate == null ? 43 : $taxRate.hashCode());
        final java.lang.Object $shareProportion = this.getShareProportion();
        result = result * PRIME + ($shareProportion == null ? 43 : $shareProportion.hashCode());
        final java.lang.Object $exchangeProportion = this.getExchangeProportion();
        result = result * PRIME + ($exchangeProportion == null ? 43 : $exchangeProportion.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AuthorIncomeProperties(taxRate=" + this.getTaxRate() + ", shareProportion=" + this.getShareProportion() + ", exchangeProportion=" + this.getExchangeProportion() + ")";
    }
}
