// Generated by delombok at Mon May 09 23:17:28 CST 2022
package com.java2nb.novel.core.config;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

/**
 * @author 11797
 */
@Component
@ConfigurationProperties(prefix = "novel.file")
public class OssProperties {
    private String endpoint;
    private String keyId;
    private String keySecret;
    private String fileHost;
    private String bucketName;
    private String webUrl;

    @java.lang.SuppressWarnings("all")
    public OssProperties() {
    }

    @java.lang.SuppressWarnings("all")
    public String getEndpoint() {
        return this.endpoint;
    }

    @java.lang.SuppressWarnings("all")
    public String getKeyId() {
        return this.keyId;
    }

    @java.lang.SuppressWarnings("all")
    public String getKeySecret() {
        return this.keySecret;
    }

    @java.lang.SuppressWarnings("all")
    public String getFileHost() {
        return this.fileHost;
    }

    @java.lang.SuppressWarnings("all")
    public String getBucketName() {
        return this.bucketName;
    }

    @java.lang.SuppressWarnings("all")
    public String getWebUrl() {
        return this.webUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndpoint(final String endpoint) {
        this.endpoint = endpoint;
    }

    @java.lang.SuppressWarnings("all")
    public void setKeyId(final String keyId) {
        this.keyId = keyId;
    }

    @java.lang.SuppressWarnings("all")
    public void setKeySecret(final String keySecret) {
        this.keySecret = keySecret;
    }

    @java.lang.SuppressWarnings("all")
    public void setFileHost(final String fileHost) {
        this.fileHost = fileHost;
    }

    @java.lang.SuppressWarnings("all")
    public void setBucketName(final String bucketName) {
        this.bucketName = bucketName;
    }

    @java.lang.SuppressWarnings("all")
    public void setWebUrl(final String webUrl) {
        this.webUrl = webUrl;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof OssProperties)) return false;
        final OssProperties other = (OssProperties) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$endpoint = this.getEndpoint();
        final java.lang.Object other$endpoint = other.getEndpoint();
        if (this$endpoint == null ? other$endpoint != null : !this$endpoint.equals(other$endpoint)) return false;
        final java.lang.Object this$keyId = this.getKeyId();
        final java.lang.Object other$keyId = other.getKeyId();
        if (this$keyId == null ? other$keyId != null : !this$keyId.equals(other$keyId)) return false;
        final java.lang.Object this$keySecret = this.getKeySecret();
        final java.lang.Object other$keySecret = other.getKeySecret();
        if (this$keySecret == null ? other$keySecret != null : !this$keySecret.equals(other$keySecret)) return false;
        final java.lang.Object this$fileHost = this.getFileHost();
        final java.lang.Object other$fileHost = other.getFileHost();
        if (this$fileHost == null ? other$fileHost != null : !this$fileHost.equals(other$fileHost)) return false;
        final java.lang.Object this$bucketName = this.getBucketName();
        final java.lang.Object other$bucketName = other.getBucketName();
        if (this$bucketName == null ? other$bucketName != null : !this$bucketName.equals(other$bucketName)) return false;
        final java.lang.Object this$webUrl = this.getWebUrl();
        final java.lang.Object other$webUrl = other.getWebUrl();
        if (this$webUrl == null ? other$webUrl != null : !this$webUrl.equals(other$webUrl)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof OssProperties;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $endpoint = this.getEndpoint();
        result = result * PRIME + ($endpoint == null ? 43 : $endpoint.hashCode());
        final java.lang.Object $keyId = this.getKeyId();
        result = result * PRIME + ($keyId == null ? 43 : $keyId.hashCode());
        final java.lang.Object $keySecret = this.getKeySecret();
        result = result * PRIME + ($keySecret == null ? 43 : $keySecret.hashCode());
        final java.lang.Object $fileHost = this.getFileHost();
        result = result * PRIME + ($fileHost == null ? 43 : $fileHost.hashCode());
        final java.lang.Object $bucketName = this.getBucketName();
        result = result * PRIME + ($bucketName == null ? 43 : $bucketName.hashCode());
        final java.lang.Object $webUrl = this.getWebUrl();
        result = result * PRIME + ($webUrl == null ? 43 : $webUrl.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "OssProperties(endpoint=" + this.getEndpoint() + ", keyId=" + this.getKeyId() + ", keySecret=" + this.getKeySecret() + ", fileHost=" + this.getFileHost() + ", bucketName=" + this.getBucketName() + ", webUrl=" + this.getWebUrl() + ")";
    }
}
